[build]
  command = "npm -C web run build -- --webpack"
  publish = "web/.next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-fund --no-audit"

[[plugins]]
  package = "@netlify/plugin-nextjs"
