import type { DomainTemplate } from './domain-template.types';

// 15-02: Domain template registry — 15 domain-aware app blueprints
// Rules: no licensed advice, no diagnosis/legal/tax/investment conclusions, public-safe only

export const DOMAIN_TEMPLATE_REGISTRY: DomainTemplate[] = [

  // ── 1. Medical / Healthcare ───────────────────────────────────────────────
  {
    id: 'healthcare-portal',
    domainAgentId: 'medical',
    name: 'Healthcare Portal',
    category: 'MEDICAL',
    regulated: true,
    summary: 'Patient-facing portal for appointment booking, health intake, and care coordination workflows.',
    recommendedUserRoles: ['patient', 'doctor', 'nurse', 'receptionist', 'admin'],
    coreFeatures: [
      'Appointment booking and scheduling',
      'Patient intake form with health history',
      'EHR viewer (read-only document display)',
      'Telemedicine video consultation room',
      'Notification system (SMS + email reminders)',
      'Provider availability calendar',
    ],
    optionalFeatures: [
      'Prescription refill request flow',
      'Lab result viewer (PDF display)',
      'Insurance claim submission helper',
      'Patient portal secure messaging',
      'Multi-location clinic support',
    ],
    dataModels: [
      { name: 'Patient', fields: ['id', 'name', 'dateOfBirth', 'contactEmail', 'phone', 'emergencyContact'] },
      { name: 'Appointment', fields: ['id', 'patientId', 'doctorId', 'datetime', 'status', 'type', 'notes'] },
      { name: 'Doctor', fields: ['id', 'name', 'specialty', 'licenseNumber', 'availabilitySlots'] },
      { name: 'MedicalRecord', fields: ['id', 'patientId', 'type', 'fileUrl', 'uploadedAt', 'providerId'] },
      { name: 'Notification', fields: ['id', 'userId', 'channel', 'body', 'sentAt', 'status'] },
    ],
    apiModules: [
      { name: 'Appointments', endpoints: ['GET /appointments', 'POST /appointments', 'PATCH /appointments/:id/status', 'DELETE /appointments/:id'] },
      { name: 'Patients', endpoints: ['GET /patients/:id', 'POST /patients', 'PATCH /patients/:id'] },
      { name: 'Providers', endpoints: ['GET /doctors', 'GET /doctors/:id/availability'] },
      { name: 'Records', endpoints: ['GET /records/:patientId', 'POST /records/upload'] },
      { name: 'Notifications', endpoints: ['POST /notifications/send', 'GET /notifications/:userId'] },
    ],
    uiFlows: [
      { name: 'Patient registration', steps: ['Sign up', 'Complete health intake form', 'Verify identity', 'Dashboard'] },
      { name: 'Book appointment', steps: ['Select provider', 'Choose date/time', 'Confirm details', 'Receive confirmation'] },
      { name: 'Telemedicine session', steps: ['Join waiting room', 'Video call with provider', 'Post-visit summary'] },
      { name: 'Provider dashboard', steps: ['View schedule', 'Review patient queue', 'Access records', 'Add notes'] },
    ],
    complianceChecklist: [
      'Implement HIPAA technical safeguards (encryption at rest and in transit)',
      'Execute BAA (Business Associate Agreement) with all vendors',
      'Add consent forms for data collection and telehealth',
      'Implement role-based access — providers see only their patients',
      'Enable immutable audit log for all PHI access',
      'Define data retention and deletion policy (HIPAA minimum 6 years)',
      'Conduct HIPAA Security Risk Assessment before launch',
    ],
    riskWarnings: [
      'Platform must NOT provide medical diagnosis or treatment recommendations',
      'Emergency/urgent care must redirect to 911 — not handled in-app',
      'All clinical content displayed must be authored/reviewed by licensed clinicians',
      'HIPAA violations carry civil and criminal penalties — legal review required',
    ],
    securityRequirements: [
      'AES-256 encryption at rest for all PHI',
      'TLS 1.3 in transit for all API calls',
      'MFA required for all provider accounts',
      'Role-based access control — patients cannot access other patient records',
      'Tamper-evident audit trail for every PHI read/write',
      'Penetration testing required before public launch',
    ],
    suggestedIntegrations: ['Twilio (SMS/video)', 'Stripe (billing)', 'Google Calendar', 'HL7 FHIR API', 'SendGrid', 'DocuSign (consent forms)'],
    starterPrompts: [
      'Build a patient appointment booking app for a family medical clinic',
      'Build a telemedicine platform with HIPAA-compliant video consultations',
      'Build a doctor scheduling and patient portal for a multi-specialty clinic',
    ],
    prohibitedClaims: ['medical diagnosis', 'treatment recommendations', 'dosage guidance', 'emergency triage', 'prescription decisions'],
    requiredDisclaimers: [
      'Not medical advice. All clinical content requires review by a licensed healthcare provider.',
      'Must comply with HIPAA. Consult a HIPAA compliance officer before launch.',
    ],
  },

  // ── 2. Legal Compliance ───────────────────────────────────────────────────
  {
    id: 'compliance-toolkit',
    domainAgentId: 'legal-compliance',
    name: 'Compliance Toolkit',
    category: 'LEGAL',
    regulated: true,
    summary: 'Legal compliance workflow tool with consent management, policy page generation, and regulatory checklists.',
    recommendedUserRoles: ['compliance officer', 'legal counsel', 'end user', 'admin'],
    coreFeatures: [
      'GDPR/CCPA consent banner and preference center',
      'Cookie consent management with audit trail',
      'Privacy policy and terms of service template builder',
      'Data Subject Request (DSR) workflow',
      'Consent version history and audit log',
      'Compliance checklist dashboard',
    ],
    optionalFeatures: [
      'E-signature integration for policy acceptance',
      'DSAR (Data Subject Access Request) automation',
      'Regulatory change alert system',
      'Third-party vendor compliance tracker',
    ],
    dataModels: [
      { name: 'ConsentRecord', fields: ['id', 'userId', 'type', 'version', 'accepted', 'timestamp', 'ipAddress'] },
      { name: 'PolicyVersion', fields: ['id', 'type', 'content', 'effectiveDate', 'authorId'] },
      { name: 'DataRequest', fields: ['id', 'userId', 'type', 'status', 'submittedAt', 'dueDate', 'resolvedAt'] },
      { name: 'AuditLog', fields: ['id', 'actorId', 'action', 'resourceType', 'resourceId', 'timestamp'] },
    ],
    apiModules: [
      { name: 'Consent', endpoints: ['POST /consent/record', 'GET /consent/:userId', 'GET /consent/audit'] },
      { name: 'Policies', endpoints: ['GET /policies/:type', 'POST /policies', 'GET /policies/history'] },
      { name: 'DataRequests', endpoints: ['POST /data-requests', 'GET /data-requests/:id', 'PATCH /data-requests/:id/status'] },
      { name: 'Audit', endpoints: ['GET /audit/logs', 'GET /audit/export'] },
    ],
    uiFlows: [
      { name: 'Consent banner', steps: ['Show on first visit', 'Accept/reject/customize', 'Record consent', 'Allow preference updates'] },
      { name: 'DSR submission', steps: ['User submits request', 'Identity verification', 'Admin review', 'Response within 30 days'] },
      { name: 'Policy management', steps: ['Draft policy version', 'Legal review workflow', 'Publish with effective date', 'Notify users'] },
    ],
    complianceChecklist: [
      'Implement GDPR Article 7 consent requirements (freely given, specific, informed)',
      'Support CCPA consumer rights (access, delete, opt-out)',
      'Cookie consent must pre-date non-essential cookie loading',
      'DSR responses required within 30 days (GDPR) / 45 days (CCPA)',
      'Record all consent with timestamp, version, and IP address',
      'Publish privacy policy and terms of service at accessible URLs',
    ],
    riskWarnings: [
      'Generated policy templates require review by a qualified attorney before use',
      'Jurisdiction-specific requirements vary — EU, UK, California, etc.',
      'Non-compliance with GDPR can result in fines up to 4% of global revenue',
    ],
    securityRequirements: [
      'Consent records must be immutable — append-only storage',
      'Audit logs tamper-evident and exportable',
      'Data minimization — collect only what is required',
      'Encryption at rest for all personal data',
    ],
    suggestedIntegrations: ['DocuSign (e-signature)', 'Osano/Cookiebot (cookie consent)', 'OneTrust', 'SendGrid (DSR notifications)', 'Segment (consent sync)'],
    starterPrompts: [
      'Build a GDPR consent management platform with cookie banner and preference center',
      'Build a privacy compliance dashboard with data subject request handling',
      'Build a legal page generator for SaaS products (terms, privacy, cookies)',
    ],
    prohibitedClaims: ['legal conclusions', 'contract enforceability opinions', 'jurisdiction-specific legal advice', 'lawsuit strategy'],
    requiredDisclaimers: [
      'Not legal advice. All generated policies require review by a qualified attorney.',
      'Consult qualified legal counsel before publishing compliance materials.',
    ],
  },

  // ── 3. Finance / Accounting ───────────────────────────────────────────────
  {
    id: 'fintech-saas',
    domainAgentId: 'finance',
    name: 'Finance & Invoicing SaaS',
    category: 'FINANCE',
    regulated: true,
    summary: 'Financial management SaaS with invoicing, expense tracking, payment processing, and reporting dashboards.',
    recommendedUserRoles: ['business owner', 'accountant', 'employee', 'client', 'admin'],
    coreFeatures: [
      'Invoice creation, sending, and payment tracking',
      'Expense submission and categorization',
      'Payment processing with Stripe/PayPal',
      'Financial dashboard with charts and KPIs',
      'Multi-currency support',
      'Tax document upload and storage',
      'Client management',
    ],
    optionalFeatures: [
      'Recurring billing and subscriptions',
      'Bank reconciliation (via Plaid)',
      'Budget planning and forecasting',
      'Payroll calculation (not tax advice)',
      'Multi-entity / multi-company support',
    ],
    dataModels: [
      { name: 'Invoice', fields: ['id', 'clientId', 'lineItems', 'subtotal', 'tax', 'total', 'status', 'dueDate', 'paidAt'] },
      { name: 'Expense', fields: ['id', 'userId', 'category', 'amount', 'currency', 'receiptUrl', 'date', 'approved'] },
      { name: 'Payment', fields: ['id', 'invoiceId', 'amount', 'method', 'transactionId', 'paidAt'] },
      { name: 'Client', fields: ['id', 'name', 'email', 'billingAddress', 'currency', 'taxId'] },
      { name: 'TaxDocument', fields: ['id', 'type', 'year', 'fileUrl', 'uploadedAt', 'userId'] },
    ],
    apiModules: [
      { name: 'Invoices', endpoints: ['GET /invoices', 'POST /invoices', 'PATCH /invoices/:id', 'POST /invoices/:id/send', 'POST /invoices/:id/mark-paid'] },
      { name: 'Expenses', endpoints: ['GET /expenses', 'POST /expenses', 'PATCH /expenses/:id/approve'] },
      { name: 'Payments', endpoints: ['POST /payments/checkout', 'GET /payments/:id', 'POST /payments/webhook'] },
      { name: 'Clients', endpoints: ['GET /clients', 'POST /clients', 'PATCH /clients/:id'] },
      { name: 'Reports', endpoints: ['GET /reports/revenue', 'GET /reports/expenses', 'GET /reports/export'] },
    ],
    uiFlows: [
      { name: 'Create and send invoice', steps: ['Add line items', 'Select client', 'Preview', 'Send by email', 'Track payment status'] },
      { name: 'Expense submission', steps: ['Upload receipt', 'Categorize', 'Submit for approval', 'Manager approves', 'Record reimbursement'] },
      { name: 'Financial dashboard', steps: ['View revenue trend', 'Check outstanding invoices', 'Expense breakdown chart', 'Export report'] },
    ],
    complianceChecklist: [
      'PCI DSS compliance for payment data handling',
      'Financial record retention (7 years in most jurisdictions)',
      'Invoice numbering must be sequential and auditable',
      'GDPR/CCPA compliance for client financial data',
      'Encryption at rest for all financial records',
    ],
    riskWarnings: [
      'Platform must NOT provide investment, tax, or financial advice',
      'Tax calculations shown are estimates only — require professional accountant review',
      'Payment processing requires PCI DSS compliance certification',
    ],
    securityRequirements: [
      'PCI DSS for payment data (tokenize, never store raw card numbers)',
      'TLS 1.3 for all API endpoints',
      'MFA for all finance team accounts',
      'Role-based access — accountants see all, employees see own expenses',
      'Immutable audit trail for all financial record changes',
    ],
    suggestedIntegrations: ['Stripe (payments)', 'Plaid (bank connections)', 'QuickBooks/Xero (accounting sync)', 'Twilio (payment reminders)', 'PDF.js (invoice PDF generation)'],
    starterPrompts: [
      'Build an invoice and payment tracking SaaS for freelancers',
      'Build a multi-tenant expense management platform with reporting',
      'Build an invoicing app with Stripe integration and client portal',
    ],
    prohibitedClaims: ['investment recommendations', 'tax advice', 'exact tax liability', 'financial guarantees', 'personalized trading advice'],
    requiredDisclaimers: [
      'Not financial or tax advice. Consult a qualified accountant or financial advisor.',
      'Tax estimates shown are informational only and require professional review.',
    ],
  },

  // ── 4. Insurance ─────────────────────────────────────────────────────────
  {
    id: 'insurance-portal',
    domainAgentId: 'insurance',
    name: 'Insurance Claims Portal',
    category: 'INSURANCE',
    regulated: true,
    summary: 'Insurance claim submission, tracking, and policy management portal with document workflows.',
    recommendedUserRoles: ['policyholder', 'claims adjuster', 'underwriter', 'broker', 'admin'],
    coreFeatures: [
      'Policy viewer and summary dashboard',
      'Claim submission form with document upload',
      'Claim status tracking timeline',
      'Adjuster assignment and case management',
      'Payment tracking for approved claims',
      'Renewal reminder notifications',
    ],
    optionalFeatures: [
      'Multi-policy management',
      'Broker portal with client portfolio view',
      'Automated document checklist per claim type',
      'Premium payment management',
    ],
    dataModels: [
      { name: 'Policy', fields: ['id', 'holderId', 'type', 'policyNumber', 'startDate', 'endDate', 'premium', 'status'] },
      { name: 'Claim', fields: ['id', 'policyId', 'type', 'description', 'amount', 'status', 'submittedAt', 'adjusterId'] },
      { name: 'ClaimDocument', fields: ['id', 'claimId', 'documentType', 'fileUrl', 'uploadedAt'] },
      { name: 'Payment', fields: ['id', 'claimId', 'amount', 'method', 'processedAt', 'status'] },
    ],
    apiModules: [
      { name: 'Policies', endpoints: ['GET /policies/:holderId', 'GET /policies/:id'] },
      { name: 'Claims', endpoints: ['POST /claims', 'GET /claims/:id', 'PATCH /claims/:id/status', 'GET /claims?holderId='] },
      { name: 'Documents', endpoints: ['POST /documents/upload', 'GET /documents/:claimId'] },
      { name: 'Notifications', endpoints: ['POST /notifications/renewal', 'GET /notifications/:userId'] },
    ],
    uiFlows: [
      { name: 'Submit claim', steps: ['Select policy', 'Describe incident', 'Upload documents', 'Submit', 'Receive confirmation number'] },
      { name: 'Track claim', steps: ['View status timeline', 'Upload additional docs if requested', 'Receive adjuster decision notification'] },
      { name: 'Adjuster workflow', steps: ['View assigned claims queue', 'Review documents', 'Request additional info', 'Record decision'] },
    ],
    complianceChecklist: [
      'Claim acknowledgement within statutory timeframe (varies by state)',
      'Document retention policy per jurisdiction requirements',
      'Privacy policy for policyholder PII',
      'Adjuster licensing requirements vary by state — verify before launch',
    ],
    riskWarnings: [
      'Coverage determinations require a licensed insurance adjuster — not automated',
      'Platform must NOT predict claim approval or denial outcomes',
      'State insurance regulations vary significantly — legal review required',
    ],
    securityRequirements: [
      'Encryption at rest for all policyholder PII',
      'Document storage with access control (adjusters see only assigned claims)',
      'Audit trail for all claim status changes',
      'Secure file upload with virus scanning',
    ],
    suggestedIntegrations: ['Twilio (SMS notifications)', 'Stripe (premium payments)', 'DocuSign (policy signing)', 'SendGrid', 'ClamAV (file scanning)'],
    starterPrompts: [
      'Build an insurance claim submission and tracking portal',
      'Build a policy management app with claim workflows for small insurance companies',
    ],
    prohibitedClaims: ['coverage approval predictions', 'claim denial likelihood', 'underwriting decisions', 'policy recommendations as licensed advice'],
    requiredDisclaimers: [
      'Not insurance advice. Coverage determinations require a licensed insurance professional.',
      'Consult a licensed insurance broker for policy recommendations.',
    ],
  },

  // ── 5. Real Estate ────────────────────────────────────────────────────────
  {
    id: 'property-listing-platform',
    domainAgentId: 'real-estate',
    name: 'Property Listing Platform',
    category: 'REAL_ESTATE',
    regulated: true,
    summary: 'Property listing, rental management, and tenant portal with lease workflows and maintenance requests.',
    recommendedUserRoles: ['tenant', 'landlord', 'property manager', 'prospective buyer', 'admin'],
    coreFeatures: [
      'Property listings with photo gallery and search',
      'Advanced search and filter (price, bedrooms, location)',
      'Rental inquiry and showing request form',
      'Online lease management (view and sign)',
      'Rent payment tracking',
      'Maintenance request system with status tracking',
    ],
    optionalFeatures: [
      'Virtual tour integration',
      'Tenant screening workflow (links to third-party service)',
      'Automated rent increase notice generator',
      'Multi-unit property management',
    ],
    dataModels: [
      { name: 'Property', fields: ['id', 'ownerId', 'address', 'type', 'bedrooms', 'rent', 'status', 'photos'] },
      { name: 'Listing', fields: ['id', 'propertyId', 'description', 'availableFrom', 'publishedAt', 'views'] },
      { name: 'Tenant', fields: ['id', 'name', 'email', 'phone', 'leaseId', 'moveInDate'] },
      { name: 'Lease', fields: ['id', 'propertyId', 'tenantId', 'startDate', 'endDate', 'rentAmount', 'signedAt'] },
      { name: 'MaintenanceRequest', fields: ['id', 'propertyId', 'tenantId', 'description', 'priority', 'status', 'createdAt'] },
    ],
    apiModules: [
      { name: 'Properties', endpoints: ['GET /properties', 'POST /properties', 'PATCH /properties/:id', 'GET /properties/:id'] },
      { name: 'Listings', endpoints: ['GET /listings?search=', 'POST /listings', 'DELETE /listings/:id'] },
      { name: 'Leases', endpoints: ['GET /leases/:tenantId', 'POST /leases', 'POST /leases/:id/sign'] },
      { name: 'Payments', endpoints: ['POST /payments/rent', 'GET /payments/history/:leaseId'] },
      { name: 'Maintenance', endpoints: ['POST /maintenance', 'GET /maintenance/:propertyId', 'PATCH /maintenance/:id/status'] },
    ],
    uiFlows: [
      { name: 'Search and apply', steps: ['Search listings', 'View property details', 'Submit inquiry', 'Schedule showing', 'Receive lease offer'] },
      { name: 'Tenant portal', steps: ['Pay rent online', 'Submit maintenance request', 'View lease documents', 'Receive notices'] },
      { name: 'Landlord dashboard', steps: ['Manage properties', 'Review inquiries', 'Track rent payments', 'Handle maintenance queue'] },
    ],
    complianceChecklist: [
      'Fair Housing Act compliance — non-discriminatory listing language',
      'Local rent control disclosure requirements where applicable',
      'Privacy policy for tenant PII',
      'Lease templates require attorney review before use',
      'Security deposit handling rules vary by state',
    ],
    riskWarnings: [
      'Eviction processes are jurisdiction-specific legal matters — not handled in-app',
      'Lease agreements require attorney review before use as binding documents',
      'Rent control and landlord-tenant laws vary significantly by city and state',
    ],
    securityRequirements: [
      'Tenant PII encrypted at rest',
      'Payment data tokenized via Stripe (never stored raw)',
      'Lease documents access-controlled (only parties to lease)',
      'Audit trail for all lease modifications',
    ],
    suggestedIntegrations: ['Stripe (rent payments)', 'DocuSign (lease signing)', 'Twilio (tenant notifications)', 'Google Maps (property location)', 'Cloudinary (photos)'],
    starterPrompts: [
      'Build a rental property management platform with tenant portal and online rent payment',
      'Build a property listing site with online lease signing and maintenance requests',
    ],
    prohibitedClaims: ['eviction legal advice', 'legal title opinions', 'mortgage recommendations', 'property valuation conclusions'],
    requiredDisclaimers: [
      'Not legal or real estate advice. Lease agreements require attorney review.',
      'Eviction and landlord/tenant legal processes require qualified legal counsel.',
    ],
  },

  // ── 6. Ecommerce ──────────────────────────────────────────────────────────
  {
    id: 'ecommerce-store',
    domainAgentId: 'ecommerce',
    name: 'Ecommerce Store',
    category: 'ECOMMERCE',
    regulated: false,
    summary: 'Full-featured online store with product catalog, shopping cart, checkout, and order management.',
    recommendedUserRoles: ['shopper', 'merchant', 'admin', 'fulfillment staff', 'customer support'],
    coreFeatures: [
      'Product catalog with categories and variants',
      'Search and filter with facets',
      'Shopping cart and saved items',
      'Multi-step checkout with address and payment',
      'Order management and status tracking',
      'Customer accounts and order history',
      'Reviews and ratings',
    ],
    optionalFeatures: ['Wishlist', 'Discount codes and promotions', 'Loyalty points', 'Multi-currency', 'Gift cards', 'Abandoned cart recovery'],
    dataModels: [
      { name: 'Product', fields: ['id', 'name', 'description', 'price', 'stock', 'images', 'category', 'variants'] },
      { name: 'Cart', fields: ['id', 'userId', 'items', 'subtotal', 'updatedAt'] },
      { name: 'Order', fields: ['id', 'userId', 'items', 'total', 'status', 'shippingAddress', 'shippedAt'] },
      { name: 'Review', fields: ['id', 'productId', 'userId', 'rating', 'body', 'createdAt'] },
      { name: 'Address', fields: ['id', 'userId', 'line1', 'city', 'state', 'country', 'zip', 'isDefault'] },
    ],
    apiModules: [
      { name: 'Products', endpoints: ['GET /products', 'GET /products/:id', 'POST /products', 'PATCH /products/:id'] },
      { name: 'Cart', endpoints: ['GET /cart', 'POST /cart/items', 'DELETE /cart/items/:id', 'PATCH /cart/items/:id'] },
      { name: 'Orders', endpoints: ['POST /orders', 'GET /orders/:id', 'GET /orders?userId=', 'PATCH /orders/:id/status'] },
      { name: 'Payments', endpoints: ['POST /payments/checkout-session', 'POST /payments/webhook'] },
      { name: 'Reviews', endpoints: ['GET /reviews?productId=', 'POST /reviews', 'DELETE /reviews/:id'] },
    ],
    uiFlows: [
      { name: 'Shopping flow', steps: ['Browse catalog', 'Search/filter', 'Product page', 'Add to cart', 'Checkout', 'Order confirmation'] },
      { name: 'Order tracking', steps: ['Order history', 'View order status', 'Track shipment', 'Leave review'] },
      { name: 'Merchant dashboard', steps: ['Manage products', 'Process orders', 'Update inventory', 'View sales reports'] },
    ],
    complianceChecklist: [
      'PCI DSS compliance for payment processing',
      'GDPR/CCPA privacy policy and cookie consent',
      'Accessibility (WCAG 2.1 AA) for checkout flow',
      'Consumer protection: clear return and refund policy',
      'Tax collection varies by jurisdiction — configure per region',
    ],
    riskWarnings: ['Payment processing requires PCI DSS compliance', 'Sales tax rules vary by state/country — use a tax API'],
    securityRequirements: ['PCI DSS tokenized payments (Stripe)', 'CSRF protection on checkout', 'Rate limiting on add-to-cart', 'Input validation on all product fields'],
    suggestedIntegrations: ['Stripe (payments)', 'ShipStation/EasyPost (shipping)', 'Mailchimp (email marketing)', 'Cloudinary (product images)', 'Google Analytics'],
    starterPrompts: [
      'Build an online store with product catalog, cart, and Stripe checkout',
      'Build an ecommerce platform with inventory management and order tracking',
    ],
    prohibitedClaims: [],
    requiredDisclaimers: [],
  },

  // ── 7. Marketplace ────────────────────────────────────────────────────────
  {
    id: 'two-sided-marketplace',
    domainAgentId: 'marketplace',
    name: 'Two-Sided Marketplace',
    category: 'MARKETPLACE',
    regulated: false,
    summary: 'Peer-to-peer marketplace with seller listings, buyer discovery, escrow payments, and commission splits.',
    recommendedUserRoles: ['buyer', 'seller', 'admin', 'support agent'],
    coreFeatures: [
      'Seller onboarding and profile creation',
      'Listing creation with photos, pricing, and categories',
      'Buyer search and discovery with filters',
      'Booking or purchase flow with escrow payment hold',
      'Commission split on completed transactions',
      'Two-way reviews and ratings',
      'In-app messaging between buyer and seller',
    ],
    optionalFeatures: ['Featured listing promotions', 'Subscription seller tiers', 'Dispute resolution workflow', 'Seller analytics dashboard'],
    dataModels: [
      { name: 'Listing', fields: ['id', 'sellerId', 'title', 'description', 'price', 'category', 'images', 'status', 'views'] },
      { name: 'Order', fields: ['id', 'listingId', 'buyerId', 'sellerId', 'amount', 'commission', 'status', 'createdAt'] },
      { name: 'EscrowTransaction', fields: ['id', 'orderId', 'amount', 'heldAt', 'releasedAt', 'status'] },
      { name: 'Message', fields: ['id', 'senderId', 'receiverId', 'orderId', 'body', 'sentAt'] },
      { name: 'Review', fields: ['id', 'orderId', 'raterId', 'targetId', 'role', 'rating', 'comment'] },
    ],
    apiModules: [
      { name: 'Listings', endpoints: ['GET /listings', 'POST /listings', 'PATCH /listings/:id', 'DELETE /listings/:id'] },
      { name: 'Orders', endpoints: ['POST /orders', 'GET /orders/:id', 'PATCH /orders/:id/confirm', 'PATCH /orders/:id/complete'] },
      { name: 'Escrow', endpoints: ['POST /escrow/hold', 'POST /escrow/release', 'POST /escrow/refund'] },
      { name: 'Messages', endpoints: ['POST /messages', 'GET /messages/thread/:orderId'] },
      { name: 'Reviews', endpoints: ['POST /reviews', 'GET /reviews?targetId='] },
      { name: 'Payouts', endpoints: ['GET /payouts/:sellerId', 'POST /payouts/schedule'] },
    ],
    uiFlows: [
      { name: 'Seller flow', steps: ['Onboard and verify identity', 'Create listing', 'Receive booking', 'Fulfill order', 'Receive payout'] },
      { name: 'Buyer flow', steps: ['Search listings', 'View seller profile', 'Book/purchase', 'Payment held in escrow', 'Confirm delivery', 'Leave review'] },
      { name: 'Dispute flow', steps: ['Buyer raises dispute', 'Admin reviews evidence', 'Decision: refund or release escrow'] },
    ],
    complianceChecklist: [
      'Marketplace facilitator tax laws (collect/remit sales tax in applicable states)',
      'KYC/AML identity verification for seller payouts above thresholds',
      'Clear dispute resolution policy in terms of service',
      'Consumer protection: buyer guarantee or escrow policy prominently displayed',
    ],
    riskWarnings: ['Commission split agreements are contractual — terms of service requires attorney review', 'Seller payout KYC requirements vary by country and transaction volume'],
    securityRequirements: ['Stripe Connect for marketplace payments (escrow)', 'Seller identity verification before first payout', 'Rate limiting on listing creation', 'Fraud detection on high-value transactions'],
    suggestedIntegrations: ['Stripe Connect (marketplace payments)', 'Twilio (buyer/seller messaging)', 'Cloudinary (listing photos)', 'Persona/Jumio (identity verification)', 'SendGrid'],
    starterPrompts: [
      'Build a peer-to-peer rental marketplace like Airbnb for equipment',
      'Build a freelance services marketplace with escrow payments and seller profiles',
      'Build a two-sided marketplace with vendor listings and commission splits',
    ],
    prohibitedClaims: [],
    requiredDisclaimers: [],
  },

  // ── 8. Restaurant / Food ──────────────────────────────────────────────────
  {
    id: 'food-ordering-app',
    domainAgentId: 'restaurant',
    name: 'Food Ordering App',
    category: 'FOOD',
    regulated: false,
    summary: 'Restaurant ordering platform with online menu, cart, delivery tracking, and kitchen management.',
    recommendedUserRoles: ['customer', 'kitchen staff', 'delivery driver', 'restaurant manager', 'admin'],
    coreFeatures: [
      'Online menu with categories and customizations',
      'Cart and checkout with delivery or pickup option',
      'Real-time order tracking map',
      'Kitchen display system (KDS) for staff',
      'Delivery zone management',
      'Table reservation system',
    ],
    optionalFeatures: ['Loyalty rewards program', 'POS integration', 'Multi-restaurant support', 'Scheduled orders', 'Contactless QR menu'],
    dataModels: [
      { name: 'Restaurant', fields: ['id', 'name', 'address', 'cuisine', 'openHours', 'deliveryRadius'] },
      { name: 'MenuItem', fields: ['id', 'restaurantId', 'name', 'price', 'category', 'options', 'available'] },
      { name: 'Order', fields: ['id', 'customerId', 'restaurantId', 'items', 'total', 'status', 'type', 'address'] },
      { name: 'DeliveryZone', fields: ['id', 'restaurantId', 'radiusKm', 'minOrder', 'deliveryFee'] },
      { name: 'Reservation', fields: ['id', 'restaurantId', 'customerId', 'partySize', 'datetime', 'status'] },
    ],
    apiModules: [
      { name: 'Menu', endpoints: ['GET /menu/:restaurantId', 'POST /menu/items', 'PATCH /menu/items/:id/availability'] },
      { name: 'Orders', endpoints: ['POST /orders', 'GET /orders/:id', 'PATCH /orders/:id/status', 'GET /orders/kitchen-queue'] },
      { name: 'Delivery', endpoints: ['GET /delivery/zones', 'POST /delivery/assign-driver', 'PATCH /delivery/:id/location'] },
      { name: 'Reservations', endpoints: ['POST /reservations', 'GET /reservations/:restaurantId', 'PATCH /reservations/:id/status'] },
    ],
    uiFlows: [
      { name: 'Customer ordering', steps: ['Browse menu', 'Customize items', 'Add to cart', 'Choose delivery/pickup', 'Pay', 'Track order'] },
      { name: 'Kitchen workflow', steps: ['New order appears on KDS', 'Mark items preparing', 'Mark ready for pickup/delivery'] },
      { name: 'Driver workflow', steps: ['Accept delivery', 'Navigate to restaurant', 'Pick up order', 'Navigate to customer', 'Confirm delivery'] },
    ],
    complianceChecklist: [
      'Allergen disclosure required by law in many markets',
      'Food safety regulations vary by jurisdiction',
      'Driver classification (employee vs. contractor) — legal review required',
      'PCI DSS for payment processing',
    ],
    riskWarnings: ['Allergen information must be accurate and complete', 'Delivery driver classification has legal implications by jurisdiction'],
    securityRequirements: ['Payment tokenization via Stripe', 'Rate limiting on order submission', 'Driver location data privacy policy', 'Webhook HMAC validation for delivery events'],
    suggestedIntegrations: ['Stripe (payments)', 'Google Maps (delivery tracking)', 'Twilio (SMS order updates)', 'Firebase (real-time order status)', 'DoorDash Drive (delivery)'],
    starterPrompts: [
      'Build a food ordering app for a single restaurant with delivery tracking',
      'Build a multi-restaurant food delivery marketplace with real-time tracking',
    ],
    prohibitedClaims: [],
    requiredDisclaimers: [],
  },

  // ── 9. Logistics / Delivery ───────────────────────────────────────────────
  {
    id: 'logistics-tracker',
    domainAgentId: 'logistics',
    name: 'Logistics & Delivery Tracker',
    category: 'LOGISTICS',
    regulated: false,
    summary: 'Shipment tracking and fleet management platform with route optimization and dispatch.',
    recommendedUserRoles: ['dispatcher', 'driver', 'warehouse staff', 'customer', 'admin'],
    coreFeatures: [
      'Shipment creation and barcode/QR label generation',
      'Real-time GPS tracking for drivers and customers',
      'Route optimization with multi-stop planning',
      'Delivery confirmation (signature, photo proof)',
      'Customer tracking page with estimated delivery',
      'Dispatch and driver assignment dashboard',
    ],
    optionalFeatures: ['Fleet vehicle management', 'Warehouse inventory management', 'Analytics and delivery performance reports', 'International shipping with customs support'],
    dataModels: [
      { name: 'Shipment', fields: ['id', 'trackingNumber', 'senderId', 'recipientAddress', 'status', 'estimatedDelivery'] },
      { name: 'Driver', fields: ['id', 'name', 'phone', 'vehicleId', 'currentLocation', 'status'] },
      { name: 'Route', fields: ['id', 'driverId', 'shipmentIds', 'optimizedStops', 'startedAt', 'completedAt'] },
      { name: 'DeliveryEvent', fields: ['id', 'shipmentId', 'event', 'location', 'timestamp', 'driverId'] },
    ],
    apiModules: [
      { name: 'Shipments', endpoints: ['POST /shipments', 'GET /shipments/:trackingNumber', 'PATCH /shipments/:id/status'] },
      { name: 'Drivers', endpoints: ['GET /drivers', 'POST /drivers', 'PATCH /drivers/:id/location'] },
      { name: 'Routes', endpoints: ['POST /routes/optimize', 'GET /routes/:driverId/active', 'PATCH /routes/:id/complete'] },
      { name: 'Tracking', endpoints: ['GET /track/:trackingNumber (public)', 'POST /tracking/events'] },
    ],
    uiFlows: [
      { name: 'Shipment creation', steps: ['Enter sender/recipient', 'Select service type', 'Generate label', 'Assign to driver/route'] },
      { name: 'Driver app', steps: ['View assigned route', 'Navigate to stop', 'Capture proof of delivery', 'Mark delivered'] },
      { name: 'Customer tracking', steps: ['Enter tracking number', 'View timeline', 'See real-time driver location', 'Receive delivery notification'] },
    ],
    complianceChecklist: [
      'Driver location tracking requires explicit consent',
      'DOT regulations for commercial vehicles (US)',
      'Customs declarations for international shipments',
      'Driver hours of service compliance',
    ],
    riskWarnings: ['Commercial vehicle operations require DOT compliance review', 'Driver location data must be handled with privacy policy'],
    securityRequirements: ['Driver location data encrypted in transit', 'Tracking page rate limited to prevent address enumeration', 'Webhook delivery events signed with HMAC', 'API key auth for warehouse integrations'],
    suggestedIntegrations: ['Google Maps (routing)', 'EasyPost/FedEx/UPS APIs (carrier rates)', 'Twilio (delivery SMS)', 'Firebase (real-time tracking)', 'Stripe (shipping payments)'],
    starterPrompts: [
      'Build a last-mile delivery tracking app with real-time driver GPS',
      'Build a fleet management and dispatch system with route optimization',
    ],
    prohibitedClaims: [],
    requiredDisclaimers: [],
  },

  // ── 10. Education / LMS ───────────────────────────────────────────────────
  {
    id: 'learning-management-system',
    domainAgentId: 'education',
    name: 'Learning Management System',
    category: 'EDUCATION',
    regulated: false,
    summary: 'Online learning platform with courses, video lessons, quizzes, and student progress tracking.',
    recommendedUserRoles: ['student', 'instructor', 'content creator', 'admin'],
    coreFeatures: [
      'Course catalog with enrollment and payment',
      'Video lesson player with progress tracking',
      'Quizzes and assessments with auto-grading',
      'Student progress dashboard',
      'Certificate generation on course completion',
      'Discussion forums per course',
    ],
    optionalFeatures: ['Live session scheduling (Zoom/Meet)', 'AI-powered adaptive learning', 'Peer review assignments', 'Gamification (points, badges)', 'Subscription plan support'],
    dataModels: [
      { name: 'Course', fields: ['id', 'instructorId', 'title', 'description', 'price', 'category', 'status'] },
      { name: 'Lesson', fields: ['id', 'courseId', 'title', 'videoUrl', 'duration', 'order', 'free'] },
      { name: 'Enrollment', fields: ['id', 'userId', 'courseId', 'enrolledAt', 'completedAt', 'paid'] },
      { name: 'Progress', fields: ['id', 'userId', 'lessonId', 'completedAt', 'score'] },
      { name: 'Certificate', fields: ['id', 'userId', 'courseId', 'issuedAt', 'certificateUrl'] },
    ],
    apiModules: [
      { name: 'Courses', endpoints: ['GET /courses', 'GET /courses/:id', 'POST /courses', 'PATCH /courses/:id'] },
      { name: 'Lessons', endpoints: ['GET /lessons/:courseId', 'POST /lessons', 'PATCH /lessons/:id/order'] },
      { name: 'Enrollments', endpoints: ['POST /enrollments', 'GET /enrollments?userId=', 'GET /enrollments/:id/progress'] },
      { name: 'Progress', endpoints: ['POST /progress/complete', 'GET /progress/:userId/:courseId'] },
      { name: 'Certificates', endpoints: ['POST /certificates/issue', 'GET /certificates/:userId'] },
    ],
    uiFlows: [
      { name: 'Student learning', steps: ['Browse catalog', 'Preview free lesson', 'Enroll and pay', 'Watch lessons', 'Complete quiz', 'Earn certificate'] },
      { name: 'Instructor creation', steps: ['Create course', 'Upload lessons', 'Set pricing', 'Publish', 'View student analytics'] },
    ],
    complianceChecklist: [
      'COPPA compliance required for students under 13',
      'Accessibility (WCAG 2.1 AA) for video player and course content',
      'Video content licensing (do not use copyrighted material without license)',
      'Refund policy clearly stated at checkout',
    ],
    riskWarnings: ['COPPA compliance required if accepting students under 13', 'Video DRM required if content is paid and high-value'],
    securityRequirements: ['Video access control (signed URLs, not public CDN links)', 'Payment data via Stripe (no raw card storage)', 'Rate limiting on quiz submission endpoints', 'User data encryption at rest'],
    suggestedIntegrations: ['Stripe (payments)', 'Mux/Vimeo (video hosting)', 'Zoom (live sessions)', 'SendGrid (enrollment notifications)', 'Cloudflare (DDoS protection)'],
    starterPrompts: [
      'Build an online course platform with video lessons and quizzes',
      'Build an AI-powered tutoring app with adaptive learning paths',
      'Build a coding bootcamp platform with projects and certificates',
    ],
    prohibitedClaims: [],
    requiredDisclaimers: [],
  },

  // ── 11. HR / Recruiting ───────────────────────────────────────────────────
  {
    id: 'job-board',
    domainAgentId: 'hr-recruiting',
    name: 'Job Board & ATS',
    category: 'HR',
    regulated: false,
    summary: 'Job board with applicant tracking system (ATS), interview scheduling, and offer management.',
    recommendedUserRoles: ['job seeker', 'recruiter', 'hiring manager', 'HR admin'],
    coreFeatures: [
      'Job posting creation with requirements and salary range',
      'Job search with filters (location, type, salary)',
      'Application submission with resume upload',
      'Applicant tracking pipeline (Kanban stages)',
      'Interview scheduling with calendar integration',
      'Offer letter generation and e-signature',
    ],
    optionalFeatures: ['AI resume screening (bias-audited)', 'Referral tracking system', 'Employer branding pages', 'Salary benchmarking (general market data)'],
    dataModels: [
      { name: 'JobPosting', fields: ['id', 'companyId', 'title', 'description', 'requirements', 'salaryMin', 'salaryMax', 'type', 'status'] },
      { name: 'Application', fields: ['id', 'jobId', 'applicantId', 'status', 'resumeUrl', 'coverLetter', 'appliedAt'] },
      { name: 'Interview', fields: ['id', 'applicationId', 'scheduledAt', 'type', 'interviewerIds', 'notes'] },
      { name: 'Offer', fields: ['id', 'applicationId', 'salary', 'startDate', 'status', 'sentAt', 'signedAt'] },
    ],
    apiModules: [
      { name: 'Jobs', endpoints: ['GET /jobs', 'GET /jobs/:id', 'POST /jobs', 'PATCH /jobs/:id/status'] },
      { name: 'Applications', endpoints: ['POST /applications', 'GET /applications?jobId=', 'PATCH /applications/:id/stage'] },
      { name: 'Interviews', endpoints: ['POST /interviews', 'GET /interviews/:applicationId', 'PATCH /interviews/:id/notes'] },
      { name: 'Offers', endpoints: ['POST /offers', 'GET /offers/:applicationId', 'POST /offers/:id/sign'] },
    ],
    uiFlows: [
      { name: 'Job seeker', steps: ['Search jobs', 'View job details', 'Apply with resume', 'Track application status', 'Receive offer'] },
      { name: 'Recruiter', steps: ['Post job', 'Review applications', 'Move to phone screen', 'Schedule interview', 'Send offer'] },
    ],
    complianceChecklist: [
      'EEO (Equal Employment Opportunity) compliance — non-discriminatory filtering',
      'GDPR/CCPA: applicant data deletion after defined retention period',
      'Ban-the-box laws vary by jurisdiction — criminal history questions require review',
      'AI screening tools must be bias-audited per EEOC guidance',
    ],
    riskWarnings: ['AI resume screening must be audited for bias before use', 'Applicant data retention limits apply — delete after defined period'],
    securityRequirements: ['Resume file virus scanning on upload', 'Applicant PII encrypted at rest', 'Recruiters see only roles they manage', 'Audit trail for all stage changes'],
    suggestedIntegrations: ['LinkedIn Jobs API (posting sync)', 'Calendly (interview scheduling)', 'DocuSign (offer signing)', 'SendGrid (notifications)', 'Greenhouse/Lever (ATS migration)'],
    starterPrompts: [
      'Build a job board with applicant tracking and interview scheduling',
      'Build an AI-powered recruiting platform with resume screening',
    ],
    prohibitedClaims: [],
    requiredDisclaimers: [],
  },

  // ── 12. CRM / Sales ───────────────────────────────────────────────────────
  {
    id: 'crm-platform',
    domainAgentId: 'crm-sales',
    name: 'CRM & Sales Platform',
    category: 'CRM',
    regulated: false,
    summary: 'CRM with deal pipeline, contact management, activity logging, and sales forecasting dashboard.',
    recommendedUserRoles: ['sales rep', 'account manager', 'sales manager', 'admin'],
    coreFeatures: [
      'Contact and company management',
      'Deal pipeline with Kanban stage view',
      'Activity log (calls, emails, meetings)',
      'Email integration (send/receive in CRM)',
      'Task and follow-up reminders',
      'Sales dashboard with pipeline value and forecasts',
    ],
    optionalFeatures: ['AI lead scoring', 'Email sequence automation', 'Meeting scheduling integration', 'Revenue forecasting', 'Territory management'],
    dataModels: [
      { name: 'Contact', fields: ['id', 'name', 'email', 'phone', 'companyId', 'ownerId', 'tags'] },
      { name: 'Deal', fields: ['id', 'contactId', 'title', 'stage', 'amount', 'probability', 'closeDate', 'ownerId'] },
      { name: 'Activity', fields: ['id', 'dealId', 'contactId', 'type', 'note', 'date', 'userId'] },
      { name: 'Company', fields: ['id', 'name', 'industry', 'website', 'employeeCount', 'revenue'] },
    ],
    apiModules: [
      { name: 'Contacts', endpoints: ['GET /contacts', 'POST /contacts', 'PATCH /contacts/:id', 'DELETE /contacts/:id'] },
      { name: 'Deals', endpoints: ['GET /deals', 'POST /deals', 'PATCH /deals/:id/stage', 'GET /deals/forecast'] },
      { name: 'Activities', endpoints: ['POST /activities', 'GET /activities?dealId=', 'GET /activities/upcoming'] },
      { name: 'Reports', endpoints: ['GET /reports/pipeline', 'GET /reports/rep-performance', 'GET /reports/forecast'] },
    ],
    uiFlows: [
      { name: 'Sales rep workflow', steps: ['View pipeline', 'Log call activity', 'Move deal to next stage', 'Set follow-up task', 'Send proposal'] },
      { name: 'Manager view', steps: ['Dashboard overview', 'Rep performance comparison', 'Forecast review', 'Deal coaching notes'] },
    ],
    complianceChecklist: [
      'GDPR/CCPA for contact data — lawful basis for storing prospect data',
      'CAN-SPAM compliance for email outreach',
      'Contact data portability on request',
      'Data deletion on request within required timeframe',
    ],
    riskWarnings: ['Email marketing requires explicit consent or legitimate interest basis', 'Contact data collected must have documented lawful basis under GDPR'],
    securityRequirements: ['Contact data encrypted at rest', 'Sales reps see only contacts assigned to them', 'Email integration OAuth tokens encrypted', 'API rate limiting on bulk contact endpoints'],
    suggestedIntegrations: ['Gmail/Outlook (email sync)', 'Calendly (meeting scheduling)', 'Stripe (revenue tracking)', 'Twilio (call logging)', 'HubSpot import (migration)'],
    starterPrompts: [
      'Build a CRM with Kanban deal pipeline and email integration',
      'Build a sales tracking app with AI lead scoring and forecasting dashboard',
    ],
    prohibitedClaims: [],
    requiredDisclaimers: [],
  },

  // ── 13. Automation / Webhook ──────────────────────────────────────────────
  {
    id: 'workflow-automation',
    domainAgentId: 'automation',
    name: 'Workflow Automation Platform',
    category: 'AUTOMATION',
    regulated: false,
    summary: 'No-code workflow automation with webhook triggers, conditional logic, scheduling, and multi-app actions.',
    recommendedUserRoles: ['workflow builder', 'developer', 'operations user', 'admin'],
    coreFeatures: [
      'Visual workflow builder with drag-and-drop',
      'Webhook trigger (inbound) with HMAC verification',
      'Scheduled trigger (cron-based)',
      'Conditional branching (if/else logic)',
      'Action library (HTTP request, email, database write)',
      'Run history with logs and error details',
      'Enable/disable workflows without deletion',
    ],
    optionalFeatures: ['Custom code step (sandboxed JS)', 'Approval step (human-in-the-loop)', 'SLA monitoring and alerts', 'Workflow template marketplace'],
    dataModels: [
      { name: 'Workflow', fields: ['id', 'userId', 'name', 'triggerType', 'triggerConfig', 'steps', 'enabled', 'createdAt'] },
      { name: 'WorkflowRun', fields: ['id', 'workflowId', 'status', 'startedAt', 'finishedAt', 'logs', 'errorMessage'] },
      { name: 'ActionStep', fields: ['id', 'workflowId', 'type', 'config', 'order', 'retryCount'] },
      { name: 'WebhookEvent', fields: ['id', 'workflowId', 'payload', 'signature', 'receivedAt', 'processed'] },
    ],
    apiModules: [
      { name: 'Workflows', endpoints: ['GET /workflows', 'POST /workflows', 'PATCH /workflows/:id', 'PATCH /workflows/:id/toggle'] },
      { name: 'Runs', endpoints: ['GET /runs?workflowId=', 'GET /runs/:id/logs', 'POST /runs/:id/replay'] },
      { name: 'Webhooks', endpoints: ['POST /webhooks/:workflowId (public receive)', 'GET /webhooks/:workflowId/config'] },
      { name: 'Actions', endpoints: ['POST /actions/execute (test run)', 'GET /actions/library'] },
    ],
    uiFlows: [
      { name: 'Build workflow', steps: ['Choose trigger type', 'Configure trigger', 'Add action steps', 'Add conditions', 'Test run', 'Enable'] },
      { name: 'Debug failed run', steps: ['Open run history', 'View step-by-step logs', 'Identify failing step', 'Fix config', 'Replay run'] },
    ],
    complianceChecklist: [
      'Webhook endpoints require HMAC signature validation',
      'API keys used in steps stored in encrypted secrets vault (never in workflow JSON)',
      'Run log data retention policy (limit PII in logs)',
      'Rate limiting on webhook ingestion endpoint',
    ],
    riskWarnings: ['Automation errors can cascade across connected systems — test in sandbox first', 'Downstream API rate limits must be respected in action steps'],
    securityRequirements: ['HMAC signature validation on all webhook events', 'Secrets vault with encryption for API keys in action steps', 'Sandboxed execution for custom code steps', 'Input sanitization on all trigger payloads'],
    suggestedIntegrations: ['Slack', 'Gmail', 'Stripe webhooks', 'GitHub', 'Airtable', 'Twilio', 'PostgreSQL', 'Redis (queue)'],
    starterPrompts: [
      'Build a Zapier-like workflow automation tool with webhook triggers and actions',
      'Build a webhook orchestration platform with conditional branching and retry logic',
    ],
    prohibitedClaims: [],
    requiredDisclaimers: [],
  },

  // ── 14. Mobile App ────────────────────────────────────────────────────────
  {
    id: 'mobile-app-starter',
    domainAgentId: 'mobile-app',
    name: 'Mobile App Starter',
    category: 'MOBILE',
    regulated: false,
    summary: 'React Native / Flutter mobile app foundation with auth, push notifications, offline sync, and deep linking.',
    recommendedUserRoles: ['mobile user', 'admin'],
    coreFeatures: [
      'User auth (email, social login, biometric unlock)',
      'Push notification opt-in with preference management',
      'Offline-first data sync with conflict resolution',
      'Deep link handling for campaigns and notifications',
      'In-app purchase flow (subscriptions or one-time)',
      'Crash reporting and performance monitoring',
      'App settings and account management',
    ],
    optionalFeatures: ['AR features', 'Google/Apple Maps integration', 'Barcode/QR scanner', 'Camera media picker', 'Bluetooth device pairing'],
    dataModels: [
      { name: 'User', fields: ['id', 'email', 'displayName', 'deviceTokens', 'preferences', 'createdAt'] },
      { name: 'PushNotification', fields: ['id', 'userId', 'title', 'body', 'data', 'sentAt', 'openedAt'] },
      { name: 'SyncQueue', fields: ['id', 'userId', 'entity', 'payload', 'syncedAt', 'status'] },
      { name: 'Purchase', fields: ['id', 'userId', 'productId', 'platform', 'transactionId', 'purchasedAt', 'expiresAt'] },
    ],
    apiModules: [
      { name: 'Auth', endpoints: ['POST /auth/register', 'POST /auth/login', 'POST /auth/refresh', 'POST /auth/logout'] },
      { name: 'Notifications', endpoints: ['POST /notifications/register-device', 'POST /notifications/send', 'PATCH /notifications/preferences'] },
      { name: 'Sync', endpoints: ['GET /sync/pull', 'POST /sync/push', 'GET /sync/status'] },
      { name: 'Purchases', endpoints: ['POST /purchases/verify', 'GET /purchases/:userId'] },
    ],
    uiFlows: [
      { name: 'Onboarding', steps: ['Splash screen', 'Sign up / login', 'Push notification permission', 'Feature tour', 'Home screen'] },
      { name: 'Offline mode', steps: ['Detect connectivity loss', 'Show offline indicator', 'Queue local changes', 'Sync on reconnect'] },
    ],
    complianceChecklist: [
      'Apple App Store Guidelines compliance review before submission',
      'Google Play Developer Policy compliance',
      'COPPA: parental consent required for users under 13',
      'Push notification consent must be explicit and revocable',
      'In-app purchase implementation must use platform-native APIs (Apple/Google)',
    ],
    riskWarnings: ['App Store review can take 1-7 days — plan accordingly', 'Biometric auth must degrade gracefully on unsupported devices', 'In-app purchase bypass attempts are common — validate receipts server-side'],
    securityRequirements: ['JWT with short expiry + refresh token rotation', 'Biometric authentication is local-only (no biometric data sent to server)', 'Certificate pinning for production API calls', 'Encrypted local storage for sensitive data (Keychain/Keystore)'],
    suggestedIntegrations: ['Firebase (push, analytics, crash)', 'RevenueCat (in-app purchases)', 'Sentry (error tracking)', 'Expo OTA (over-the-air updates)', 'Branch (deep links)', 'Amplitude (analytics)'],
    starterPrompts: [
      'Build a React Native mobile app with auth, push notifications, and offline support',
      'Build a Flutter app with subscription in-app purchases and deep linking',
    ],
    prohibitedClaims: [],
    requiredDisclaimers: [],
  },

  // ── 15. Gaming Platform ───────────────────────────────────────────────────
  {
    id: 'game-platform',
    domainAgentId: 'gaming',
    name: 'Game Platform',
    category: 'GAMING',
    regulated: false,
    summary: 'Gaming platform with leaderboards, achievements, matchmaking, multiplayer sessions, and in-game economy.',
    recommendedUserRoles: ['player', 'game admin', 'moderator'],
    coreFeatures: [
      'Player profile with level, XP, and stats',
      'Global and friends leaderboards',
      'Achievement and badge system',
      'Matchmaking with skill-based grouping',
      'Real-time multiplayer session management',
      'In-game virtual currency and item inventory',
      'Anti-cheat framework (server-side validation)',
    ],
    optionalFeatures: ['Tournament bracket system', 'Clan/guild management', 'Match replay system', 'Spectator mode', 'Seasonal battle pass'],
    dataModels: [
      { name: 'Player', fields: ['id', 'username', 'level', 'xp', 'wins', 'losses', 'rank', 'createdAt'] },
      { name: 'Match', fields: ['id', 'players', 'gameMode', 'startedAt', 'endedAt', 'result', 'replayUrl'] },
      { name: 'Achievement', fields: ['id', 'playerId', 'type', 'name', 'unlockedAt'] },
      { name: 'LeaderboardEntry', fields: ['id', 'playerId', 'boardType', 'score', 'rank', 'updatedAt'] },
      { name: 'InventoryItem', fields: ['id', 'playerId', 'itemType', 'itemId', 'acquiredAt', 'quantity'] },
    ],
    apiModules: [
      { name: 'Players', endpoints: ['GET /players/:id', 'GET /players/:id/stats', 'PATCH /players/:id/xp'] },
      { name: 'Matchmaking', endpoints: ['POST /matchmaking/queue', 'DELETE /matchmaking/leave', 'GET /matchmaking/status'] },
      { name: 'Sessions', endpoints: ['POST /sessions', 'GET /sessions/:id', 'POST /sessions/:id/result'] },
      { name: 'Leaderboards', endpoints: ['GET /leaderboards/:type', 'GET /leaderboards/:type/friends'] },
      { name: 'Achievements', endpoints: ['GET /achievements/:playerId', 'POST /achievements/unlock'] },
      { name: 'Inventory', endpoints: ['GET /inventory/:playerId', 'POST /inventory/purchase', 'POST /inventory/grant'] },
    ],
    uiFlows: [
      { name: 'Match flow', steps: ['Join queue', 'Matchmaking in progress', 'Match found', 'Game session', 'Results screen', 'XP and rewards'] },
      { name: 'Progression', steps: ['View player profile', 'Check achievement list', 'Leaderboard position', 'Redeem seasonal rewards'] },
    ],
    complianceChecklist: [
      'ESRB/PEGI age rating required before publishing',
      'COPPA compliance for players under 13',
      'Loot box regulations vary by country — some require odds disclosure or are banned',
      'GDPR for EU player data',
      'App store in-app purchase policies (use platform APIs only)',
    ],
    riskWarnings: ['Real-money purchases require app store and jurisdiction compliance review', 'Loot boxes are regulated or banned in some countries', 'Anti-cheat requires server-authoritative game logic — client-side trust is insufficient'],
    securityRequirements: ['Server-authoritative match result validation (never trust client scores)', 'Rate limiting on match result submission endpoint', 'WebSocket connection authentication with JWT', 'DDoS protection for game servers (Cloudflare/AWS Shield)', 'Suspicious activity detection for account sharing/boosting'],
    suggestedIntegrations: ['PlayFab/GameSparks (game backend)', 'Redis (leaderboards, matchmaking queue)', 'Stripe (purchases)', 'Discord (community)', 'Sentry (error tracking)', 'Amplitude (player analytics)'],
    starterPrompts: [
      'Build a multiplayer game platform with leaderboards, achievements, and matchmaking',
      'Build a competitive gaming app with skill-based matchmaking and anti-cheat',
    ],
    prohibitedClaims: [],
    requiredDisclaimers: [],
  },
];

export function getTemplateById(id: string): DomainTemplate | undefined {
  return DOMAIN_TEMPLATE_REGISTRY.find((t) => t.id === id);
}

export function getTemplateByAgentId(agentId: string): DomainTemplate | undefined {
  return DOMAIN_TEMPLATE_REGISTRY.find((t) => t.domainAgentId === agentId);
}
