import type { AgentManifest } from './agent-manifest.types';

// 17-02: 10 seeded marketplace packs — metadata-only, no executable code

export const MARKETPLACE_REGISTRY: AgentManifest[] = [
  {
    id: 'mp-001',
    slug: 'healthcare-starter-pack',
    name: 'Healthcare Starter Pack',
    version: '2.1.0',
    author: 'AI Factory Official',
    verified: true,
    trustBadges: ['VERIFIED', 'OFFICIAL', 'REGULATED'],
    category: 'healthcare',
    tags: ['medical', 'appointments', 'hipaa', 'telehealth', 'clinic', 'patients', 'regulated'],
    description: 'Complete healthcare workflow pack — appointments, patient records, telehealth, and HIPAA-compliant data handling. Includes provider verification workflow and consent management.',
    icon: '🏥',
    supportedDomains: ['medical'],
    supportedUserModes: ['NON_TECHNICAL', 'BUSINESS_OWNER', 'PROFESSIONAL_DEVELOPER', 'STARTUP_FOUNDER'],
    capabilities: [
      { id: 'hc-appt',    name: 'Appointment Booking',        description: 'Online appointment scheduling with provider availability calendar.' },
      { id: 'hc-records', name: 'Patient Records',            description: 'HIPAA-compliant patient record storage with access control.' },
      { id: 'hc-video',   name: 'Telehealth Video',           description: 'Encrypted video consultation room with session recording.' },
      { id: 'hc-consent', name: 'Consent Management',         description: 'Digital consent forms with versioned audit trail.' },
      { id: 'hc-verify',  name: 'Provider Verification',      description: 'License and credential verification workflow for healthcare providers.' },
    ],
    requiredPermissions: ['domain:medical', 'guarded:enabled', 'audit:logging'],
    regulated: true,
    guardedModeRequired: true,
    pricingModel: 'FREEMIUM',
    installCount: 12400,
    rating: 4.8,
    visibility: 'PUBLIC',
    compatibility: { minSerialVersion: 16, requiredSerials: [13, 14, 15, 16], conflictsWith: [] },
    dependencies: [],
    starterPrompts: [
      'Build a doctor appointment booking system for my clinic',
      'Create a telehealth platform with video consultations',
      'Build a patient portal with HIPAA-compliant records',
    ],
    screenshots: [
      'Appointment calendar with provider availability and patient booking flow',
      'Patient dashboard showing upcoming appointments, records, and prescriptions',
      'Provider verification workflow with license status indicators',
    ],
    changelog: ['2.1.0: Added telehealth video module', '2.0.0: HIPAA audit trail', '1.0.0: Initial release'],
    includedDomainAgentIds: ['medical'],
    includedTemplateIds: ['healthcare-portal'],
    complianceNotes: [
      'Requires HIPAA BAA with cloud provider before production launch.',
      'PHI must be encrypted at rest (AES-256) and in transit (TLS 1.3).',
      'Platform cannot provide diagnosis, dosage, or prescription advice.',
      'Provider license verification required — consult qualified healthcare professional.',
    ],
    supportedCountries: ['US', 'CA', 'AU', 'GB'],
  },

  {
    id: 'mp-002',
    slug: 'ecommerce-pro-pack',
    name: 'Ecommerce Pro Pack',
    version: '3.0.1',
    author: 'AI Factory Official',
    verified: true,
    trustBadges: ['VERIFIED', 'OFFICIAL'],
    category: 'ecommerce',
    tags: ['ecommerce', 'store', 'products', 'cart', 'stripe', 'shopify-alternative', 'payments'],
    description: 'Full-featured ecommerce store pack with product catalog, cart, checkout, Stripe payments, inventory, shipping, and analytics. Launch a production-ready store in hours.',
    icon: '🛍️',
    supportedDomains: ['ecommerce'],
    supportedUserModes: ['NON_TECHNICAL', 'BUSINESS_OWNER', 'PROFESSIONAL_DEVELOPER', 'STARTUP_FOUNDER', 'AGENCY_FREELANCER'],
    capabilities: [
      { id: 'ec-catalog',  name: 'Product Catalog',     description: 'Rich product listings with variants, images, and inventory tracking.' },
      { id: 'ec-cart',     name: 'Cart & Checkout',      description: 'Multi-step checkout with address, shipping, and payment.' },
      { id: 'ec-payments', name: 'Stripe Payments',      description: 'PCI-compliant Stripe integration with webhooks and refunds.' },
      { id: 'ec-orders',   name: 'Order Management',     description: 'Order lifecycle: placed → confirmed → shipped → delivered → reviewed.' },
      { id: 'ec-analytics',name: 'Sales Analytics',      description: 'Revenue dashboard, conversion funnel, and product performance.' },
    ],
    requiredPermissions: ['domain:ecommerce', 'payments:stripe'],
    regulated: false,
    guardedModeRequired: false,
    pricingModel: 'FREEMIUM',
    installCount: 28900,
    rating: 4.7,
    visibility: 'PUBLIC',
    compatibility: { minSerialVersion: 16, requiredSerials: [13, 15], conflictsWith: ['marketplace-builder-pack'] },
    dependencies: [],
    starterPrompts: [
      'Build an online store for my handmade jewelry brand',
      'Create an ecommerce platform with Stripe checkout',
      'Build a product catalog with inventory management',
    ],
    screenshots: [
      'Product catalog grid with filters, variants, and add-to-cart',
      'Stripe checkout flow with address autofill and order summary',
      'Admin dashboard with sales charts and inventory alerts',
    ],
    changelog: ['3.0.1: Stripe webhook retry logic', '3.0.0: Analytics dashboard', '2.x: Legacy'],
    includedDomainAgentIds: ['ecommerce'],
    includedTemplateIds: ['ecommerce-store'],
    complianceNotes: ['PCI-DSS: never store raw card data — Stripe tokenization required.'],
    supportedCountries: ['GLOBAL'],
  },

  {
    id: 'mp-003',
    slug: 'marketplace-builder-pack',
    name: 'Marketplace Builder Pack',
    version: '1.5.0',
    author: 'AI Factory Official',
    verified: true,
    trustBadges: ['VERIFIED', 'OFFICIAL'],
    category: 'marketplace',
    tags: ['marketplace', 'two-sided', 'sellers', 'buyers', 'escrow', 'stripe-connect', 'platform'],
    description: 'Build Airbnb, Etsy, or Fiverr-style two-sided marketplaces. Includes seller onboarding, escrow payments, listing management, identity verification, dispute resolution, and commission engine.',
    icon: '🛒',
    supportedDomains: ['marketplace', 'ecommerce'],
    supportedUserModes: ['PROFESSIONAL_DEVELOPER', 'STARTUP_FOUNDER', 'AGENCY_FREELANCER'],
    capabilities: [
      { id: 'mb-seller',   name: 'Seller Onboarding',     description: 'KYC identity verification and Stripe Connect account setup.' },
      { id: 'mb-escrow',   name: 'Escrow Payments',        description: 'Hold funds in escrow until buyer confirms delivery or service.' },
      { id: 'mb-listings', name: 'Listing Management',     description: 'Listing creation, moderation queue, and search/filter engine.' },
      { id: 'mb-reviews',  name: 'Two-Way Reviews',        description: 'Post-transaction reviews from both buyers and sellers.' },
      { id: 'mb-dispute',  name: 'Dispute Resolution',     description: 'Structured dispute workflow with admin mediation tools.' },
      { id: 'mb-commission',name: 'Commission Engine',     description: 'Configurable commission rates with automated reconciliation.' },
    ],
    requiredPermissions: ['domain:marketplace', 'payments:stripe-connect', 'kyc:enabled'],
    regulated: false,
    guardedModeRequired: false,
    pricingModel: 'PAID',
    installCount: 8700,
    rating: 4.6,
    visibility: 'PUBLIC',
    compatibility: { minSerialVersion: 16, requiredSerials: [13, 15, 16], conflictsWith: [] },
    dependencies: [],
    starterPrompts: [
      'Build a freelance marketplace like Fiverr with escrow payments',
      'Create a two-sided rental marketplace with buyer/seller reviews',
      'Build a craft marketplace with commission-based payouts',
    ],
    screenshots: [
      'Seller dashboard: listings, earnings, Stripe Connect status',
      'Buyer discovery: search, filters, listing cards with trust badges',
      'Dispute workflow: timeline, evidence upload, admin resolution panel',
    ],
    changelog: ['1.5.0: Dispute resolution module', '1.4.0: Stripe Connect payouts', '1.0.0: Initial release'],
    includedDomainAgentIds: ['marketplace', 'ecommerce'],
    includedTemplateIds: ['two-sided-marketplace', 'ecommerce-store'],
    complianceNotes: [
      'Stripe Connect: platform must agree to Stripe Connected Account terms.',
      'KYC: identity verification required for sellers in most jurisdictions.',
    ],
    supportedCountries: ['GLOBAL'],
  },

  {
    id: 'mp-004',
    slug: 'restaurant-ops-pack',
    name: 'Restaurant Ops Pack',
    version: '2.3.0',
    author: 'AI Factory Official',
    verified: true,
    trustBadges: ['VERIFIED', 'OFFICIAL'],
    category: 'restaurant',
    tags: ['restaurant', 'food', 'delivery', 'menu', 'orders', 'rider', 'pos', 'kitchen'],
    description: 'Complete restaurant operations suite — online ordering, menu management, kitchen display, rider dispatch, and delivery tracking. Works for single locations and multi-branch chains.',
    icon: '🍽️',
    supportedDomains: ['restaurant', 'logistics'],
    supportedUserModes: ['NON_TECHNICAL', 'BUSINESS_OWNER', 'STARTUP_FOUNDER'],
    capabilities: [
      { id: 'ro-menu',     name: 'Menu Management',      description: 'Multi-category menus with modifiers, photos, and real-time availability.' },
      { id: 'ro-orders',   name: 'Online Ordering',      description: 'Web and mobile ordering with table selection or delivery address.' },
      { id: 'ro-kitchen',  name: 'Kitchen Display',       description: 'Real-time kitchen order queue with prep-time countdown timers.' },
      { id: 'ro-dispatch', name: 'Rider Dispatch',        description: 'Nearest-rider assignment with geofenced zone enforcement.' },
      { id: 'ro-tracking', name: 'Live Delivery Tracking',description: 'Real-time GPS tracking for customers and restaurant ops teams.' },
    ],
    requiredPermissions: ['domain:restaurant', 'domain:logistics', 'realtime:websocket'],
    regulated: false,
    guardedModeRequired: false,
    pricingModel: 'FREEMIUM',
    installCount: 15300,
    rating: 4.5,
    visibility: 'PUBLIC',
    compatibility: { minSerialVersion: 16, requiredSerials: [13, 15], conflictsWith: [] },
    dependencies: [],
    starterPrompts: [
      'Build a food delivery app for my restaurant chain',
      'Create an online ordering system with kitchen display',
      'Build a rider dispatch platform for food delivery',
    ],
    screenshots: [
      'Customer ordering flow: menu browsing, cart, checkout, and live tracking',
      'Kitchen display: active orders sorted by prep time with status controls',
      'Rider map view: active deliveries, pickup zones, and earnings summary',
    ],
    changelog: ['2.3.0: Multi-branch support', '2.2.0: Kitchen display system', '1.0.0: Initial release'],
    includedDomainAgentIds: ['restaurant', 'logistics'],
    includedTemplateIds: ['food-ordering-app', 'logistics-tracker'],
    complianceNotes: ['Food safety compliance varies by country — verify local regulations before launch.'],
    supportedCountries: ['GLOBAL'],
  },

  {
    id: 'mp-005',
    slug: 'saas-launch-pack',
    name: 'SaaS Launch Pack',
    version: '4.0.0',
    author: 'AI Factory Official',
    verified: true,
    trustBadges: ['VERIFIED', 'OFFICIAL', 'REGULATED'],
    category: 'saas',
    tags: ['saas', 'subscription', 'billing', 'stripe', 'multitenancy', 'finance', 'b2b', 'mrr'],
    description: 'Launch a production-ready SaaS with subscription billing, multi-tenancy, usage metering, invoicing, and a revenue dashboard. Designed for B2B and B2C subscription products.',
    icon: '🚀',
    supportedDomains: ['finance', 'automation'],
    supportedUserModes: ['PROFESSIONAL_DEVELOPER', 'STARTUP_FOUNDER', 'AGENCY_FREELANCER'],
    capabilities: [
      { id: 'sl-billing',   name: 'Subscription Billing',    description: 'Stripe subscription plans with proration, upgrades, and dunning.' },
      { id: 'sl-tenancy',   name: 'Multi-Tenancy',           description: 'Row-level security per organization with tenant-scoped JWT.' },
      { id: 'sl-metering',  name: 'Usage Metering',          description: 'Track and bill API calls, seats, or storage usage per plan.' },
      { id: 'sl-invoicing', name: 'Invoicing',               description: 'Automated PDF invoice generation and email delivery.' },
      { id: 'sl-revenue',   name: 'Revenue Dashboard',       description: 'MRR, ARR, churn, and LTV metrics with Stripe sync.' },
    ],
    requiredPermissions: ['domain:finance', 'payments:stripe', 'audit:logging'],
    regulated: true,
    guardedModeRequired: true,
    pricingModel: 'PAID',
    installCount: 34200,
    rating: 4.9,
    visibility: 'PUBLIC',
    compatibility: { minSerialVersion: 16, requiredSerials: [13, 14, 15, 16], conflictsWith: [] },
    dependencies: [],
    starterPrompts: [
      'Build a subscription SaaS platform with multi-tenant billing',
      'Create a B2B platform with usage-based pricing and invoicing',
      'Build a fintech SaaS with MRR and churn analytics',
    ],
    screenshots: [
      'Pricing page with plan comparison, feature gates, and Stripe checkout',
      'Tenant dashboard: usage metrics, billing history, and plan management',
      'Admin revenue dashboard: MRR trend, churn analysis, and cohort retention',
    ],
    changelog: ['4.0.0: Usage metering engine', '3.x: Multi-tenancy overhaul', '1.0.0: Initial release'],
    includedDomainAgentIds: ['finance', 'automation'],
    includedTemplateIds: ['fintech-saas', 'workflow-automation'],
    complianceNotes: [
      'Financial data requires idempotency keys on all payment endpoints.',
      'Tax compliance varies by country — integrate Stripe Tax or consult a tax professional.',
    ],
    supportedCountries: ['GLOBAL'],
  },

  {
    id: 'mp-006',
    slug: 'education-platform-pack',
    name: 'Education Platform Pack',
    version: '1.8.0',
    author: 'AI Factory Official',
    verified: true,
    trustBadges: ['VERIFIED', 'OFFICIAL'],
    category: 'education',
    tags: ['education', 'lms', 'courses', 'learning', 'students', 'instructors', 'certificates', 'video'],
    description: 'Build an Udemy or Coursera-style learning platform. Includes course builder, video hosting, progress tracking, quizzes, certificates, and instructor payouts.',
    icon: '🎓',
    supportedDomains: ['education', 'hr-recruiting'],
    supportedUserModes: ['NON_TECHNICAL', 'BUSINESS_OWNER', 'STARTUP_FOUNDER', 'AGENCY_FREELANCER'],
    capabilities: [
      { id: 'ep-courses',   name: 'Course Builder',          description: 'Drag-and-drop course creator with video, text, and quiz modules.' },
      { id: 'ep-progress',  name: 'Progress Tracking',       description: 'Per-student completion percentage with resume-where-left-off.' },
      { id: 'ep-quizzes',   name: 'Quizzes & Assessments',   description: 'Graded quizzes with auto-scoring and retake policies.' },
      { id: 'ep-certs',     name: 'Certificates',            description: 'Auto-generated completion certificates with verifiable QR codes.' },
      { id: 'ep-payouts',   name: 'Instructor Payouts',      description: 'Revenue share model with Stripe payouts to course creators.' },
    ],
    requiredPermissions: ['domain:education', 'media:video-upload'],
    regulated: false,
    guardedModeRequired: false,
    pricingModel: 'FREEMIUM',
    installCount: 11600,
    rating: 4.4,
    visibility: 'PUBLIC',
    compatibility: { minSerialVersion: 16, requiredSerials: [13, 15], conflictsWith: [] },
    dependencies: [],
    starterPrompts: [
      'Build a course platform where instructors can sell video courses',
      'Create a corporate training LMS with progress tracking',
      'Build an online certification platform with quizzes',
    ],
    screenshots: [
      'Student dashboard: enrolled courses, progress bars, and certificate shelf',
      'Course player: video with transcript, notes panel, and quiz sidebar',
      'Instructor analytics: student completion, revenue share, and course ratings',
    ],
    changelog: ['1.8.0: Certificate QR verification', '1.5.0: Instructor payouts', '1.0.0: Initial release'],
    includedDomainAgentIds: ['education', 'hr-recruiting'],
    includedTemplateIds: ['learning-management-system', 'job-board'],
    complianceNotes: ['Video content may require COPPA compliance for platforms serving users under 13.'],
    supportedCountries: ['GLOBAL'],
  },

  {
    id: 'mp-007',
    slug: 'logistics-delivery-pack',
    name: 'Logistics Delivery Pack',
    version: '1.2.0',
    author: 'AI Factory Official',
    verified: true,
    trustBadges: ['VERIFIED', 'OFFICIAL'],
    category: 'logistics',
    tags: ['logistics', 'delivery', 'shipments', 'tracking', 'drivers', 'fleet', 'route-optimization'],
    description: 'End-to-end logistics and delivery management — shipment creation, route optimization, driver assignment, real-time GPS tracking, and proof of delivery.',
    icon: '🚚',
    supportedDomains: ['logistics'],
    supportedUserModes: ['BUSINESS_OWNER', 'PROFESSIONAL_DEVELOPER', 'STARTUP_FOUNDER'],
    capabilities: [
      { id: 'ld-shipments', name: 'Shipment Management',     description: 'Create, label, and track shipments across multiple carriers.' },
      { id: 'ld-routing',   name: 'Route Optimization',      description: 'Multi-stop route optimization with traffic-aware ETA.' },
      { id: 'ld-drivers',   name: 'Driver Mobile App',       description: 'Driver task list, turn-by-turn navigation, and delivery confirmation.' },
      { id: 'ld-tracking',  name: 'Customer Tracking Page',  description: 'Shareable live-tracking link with ETA and map view.' },
      { id: 'ld-pod',       name: 'Proof of Delivery',       description: 'Photo capture and signature on delivery confirmation.' },
    ],
    requiredPermissions: ['domain:logistics', 'realtime:websocket', 'geo:maps'],
    regulated: false,
    guardedModeRequired: false,
    pricingModel: 'FREE',
    installCount: 9200,
    rating: 4.3,
    visibility: 'PUBLIC',
    compatibility: { minSerialVersion: 16, requiredSerials: [13, 15], conflictsWith: [] },
    dependencies: [],
    starterPrompts: [
      'Build a last-mile delivery platform for my logistics company',
      'Create a shipment tracking system for e-commerce fulfilment',
      'Build a driver dispatch app with route optimization',
    ],
    screenshots: [
      'Operations dashboard: active shipments map, driver locations, and delay alerts',
      'Driver app: task list with turn-by-turn routing and proof-of-delivery capture',
      'Customer tracking page: live map, ETA countdown, and delivery steps',
    ],
    changelog: ['1.2.0: Route optimization engine', '1.1.0: Proof of delivery', '1.0.0: Initial release'],
    includedDomainAgentIds: ['logistics'],
    includedTemplateIds: ['logistics-tracker'],
    complianceNotes: ['Driver data and location tracking may require GDPR consent in EU markets.'],
    supportedCountries: ['GLOBAL'],
  },

  {
    id: 'mp-008',
    slug: 'creator-studio-pack',
    name: 'Creator Studio Pack',
    version: '1.0.3',
    author: 'AI Factory Official',
    verified: true,
    trustBadges: ['VERIFIED', 'COMMUNITY'],
    category: 'creator',
    tags: ['creator', 'content', 'mobile', 'portfolio', 'social', 'monetization', 'fanbase', 'crm'],
    description: 'Build creator economy apps — portfolio sites, fan subscription platforms, mobile content apps, and creator CRM tools. Designed for influencers, coaches, and content businesses.',
    icon: '🎨',
    supportedDomains: ['mobile-app', 'crm-sales'],
    supportedUserModes: ['NON_TECHNICAL', 'STARTUP_FOUNDER', 'AGENCY_FREELANCER'],
    capabilities: [
      { id: 'cs-portfolio', name: 'Creator Portfolio',        description: 'Showcase work, testimonials, and services on a branded landing page.' },
      { id: 'cs-fans',      name: 'Fan Subscription',         description: 'Monthly fan subscriptions with exclusive content access tiers.' },
      { id: 'cs-mobile',    name: 'Mobile Content App',       description: 'React Native app with push notifications and offline content.' },
      { id: 'cs-crm',       name: 'Fan CRM',                  description: 'Track fan interactions, send newsletters, and segment audiences.' },
    ],
    requiredPermissions: ['domain:mobile-app', 'domain:crm-sales', 'media:uploads'],
    regulated: false,
    guardedModeRequired: false,
    pricingModel: 'FREEMIUM',
    installCount: 18500,
    rating: 4.2,
    visibility: 'PUBLIC',
    compatibility: { minSerialVersion: 16, requiredSerials: [13, 15], conflictsWith: [] },
    dependencies: [],
    starterPrompts: [
      'Build a fan subscription platform for my coaching business',
      'Create a creator portfolio with monthly membership tiers',
      'Build a mobile app for my content brand with push notifications',
    ],
    screenshots: [
      'Creator landing page: hero, portfolio grid, testimonials, and subscription CTA',
      'Fan subscription tiers: free, supporter, and VIP with content access gates',
      'Creator CRM: fan list, engagement score, and newsletter campaign builder',
    ],
    changelog: ['1.0.3: Push notification improvements', '1.0.1: Fan CRM beta', '1.0.0: Initial release'],
    includedDomainAgentIds: ['mobile-app', 'crm-sales'],
    includedTemplateIds: ['mobile-app-starter', 'crm-platform'],
    complianceNotes: ['Fan payment processing requires Stripe terms acceptance.'],
    supportedCountries: ['GLOBAL'],
  },

  {
    id: 'mp-009',
    slug: 'crm-growth-pack',
    name: 'CRM Growth Pack',
    version: '2.0.0',
    author: 'AI Factory Official',
    verified: true,
    trustBadges: ['VERIFIED', 'OFFICIAL'],
    category: 'crm',
    tags: ['crm', 'sales', 'pipeline', 'leads', 'deals', 'email', 'follow-up', 'b2b', 'growth'],
    description: 'Sales CRM with pipeline management, lead scoring, automated follow-ups, deal tracking, and revenue forecasting. Designed for B2B sales teams from 1 to 100 reps.',
    icon: '📈',
    supportedDomains: ['crm-sales'],
    supportedUserModes: ['BUSINESS_OWNER', 'PROFESSIONAL_DEVELOPER', 'STARTUP_FOUNDER', 'AGENCY_FREELANCER'],
    capabilities: [
      { id: 'cg-pipeline',  name: 'Sales Pipeline',          description: 'Kanban-style deal pipeline with stage automation and win probability.' },
      { id: 'cg-leads',     name: 'Lead Scoring',            description: 'AI-assisted lead scoring based on activity and profile fit.' },
      { id: 'cg-followup',  name: 'Automated Follow-ups',    description: 'Sequence-based email follow-ups triggered by deal stage changes.' },
      { id: 'cg-forecast',  name: 'Revenue Forecasting',     description: 'Weighted pipeline forecast with rep performance breakdown.' },
      { id: 'cg-calls',     name: 'Call Logging',            description: 'One-click call log with notes, duration, and outcome tagging.' },
    ],
    requiredPermissions: ['domain:crm-sales', 'email:sendgrid'],
    regulated: false,
    guardedModeRequired: false,
    pricingModel: 'FREEMIUM',
    installCount: 22100,
    rating: 4.6,
    visibility: 'PUBLIC',
    compatibility: { minSerialVersion: 16, requiredSerials: [13, 15], conflictsWith: [] },
    dependencies: [],
    starterPrompts: [
      'Build a CRM for my B2B sales team with pipeline management',
      'Create a lead tracking system with automated email follow-ups',
      'Build a sales forecasting tool with rep performance analytics',
    ],
    screenshots: [
      'Pipeline board: deal cards with value, stage, owner, and close date',
      'Lead profile: activity timeline, score breakdown, and next action suggestion',
      'Forecast view: weighted pipeline by rep, region, and close-date quarter',
    ],
    changelog: ['2.0.0: Revenue forecasting engine', '1.5.0: Automated sequences', '1.0.0: Initial release'],
    includedDomainAgentIds: ['crm-sales'],
    includedTemplateIds: ['crm-platform'],
    complianceNotes: ['Email marketing requires CAN-SPAM and GDPR opt-in compliance.'],
    supportedCountries: ['GLOBAL'],
  },

  {
    id: 'mp-010',
    slug: 'ai-automation-pack',
    name: 'AI Automation Pack',
    version: '1.3.0',
    author: 'AI Factory Official',
    verified: true,
    trustBadges: ['VERIFIED', 'OFFICIAL', 'ENTERPRISE_READY'],
    category: 'automation',
    tags: ['automation', 'workflow', 'no-code', 'triggers', 'actions', 'integrations', 'zapier-alternative', 'enterprise'],
    description: 'Build internal automation platforms, workflow builders, and integration hubs. Connect your apps, automate repetitive tasks, and build no-code workflow editors for your team.',
    icon: '⚡',
    supportedDomains: ['automation'],
    supportedUserModes: ['BUSINESS_OWNER', 'PROFESSIONAL_DEVELOPER', 'STARTUP_FOUNDER', 'AGENCY_FREELANCER'],
    capabilities: [
      { id: 'aa-workflows', name: 'Visual Workflow Builder',  description: 'Drag-and-drop workflow editor with trigger/condition/action nodes.' },
      { id: 'aa-triggers',  name: 'Event Triggers',           description: 'Webhook, schedule, form submission, and database-change triggers.' },
      { id: 'aa-integrations',name: 'App Integrations',       description: 'Pre-built connectors for Slack, Notion, Google Sheets, and webhooks.' },
      { id: 'aa-history',   name: 'Execution History',        description: 'Run history with step-level logs, retry controls, and failure alerts.' },
      { id: 'aa-templates', name: 'Workflow Templates',       description: 'Library of pre-built automation templates for common business tasks.' },
    ],
    requiredPermissions: ['domain:automation', 'webhooks:send', 'webhooks:receive'],
    regulated: false,
    guardedModeRequired: false,
    pricingModel: 'FREE',
    installCount: 31400,
    rating: 4.5,
    visibility: 'PUBLIC',
    compatibility: { minSerialVersion: 16, requiredSerials: [13, 15], conflictsWith: [] },
    dependencies: [],
    starterPrompts: [
      'Build an internal workflow automation platform for my operations team',
      'Create a no-code integration hub connecting our apps',
      'Build a Zapier-alternative for my company with custom triggers',
    ],
    screenshots: [
      'Workflow canvas: trigger node, condition branches, and action nodes with connectors',
      'Integration library: pre-built connectors with one-click auth',
      'Execution log: run history with step-level status, duration, and error details',
    ],
    changelog: ['1.3.0: Workflow templates library', '1.2.0: Retry and failure alerts', '1.0.0: Initial release'],
    includedDomainAgentIds: ['automation'],
    includedTemplateIds: ['workflow-automation'],
    complianceNotes: ['Data processed through integrations may cross jurisdictions — review data residency requirements.'],
    supportedCountries: ['GLOBAL'],
  },
];

export function getPackBySlug(slug: string): AgentManifest | undefined {
  return MARKETPLACE_REGISTRY.find((p) => p.slug === slug);
}
